INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (1,"Routine");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (2,"Reinspection - Routine");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (3,"Complaint");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (4,"Reinspection - Complaint");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (5,"Plan Check");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (6,"Reinspection - Plan Check");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (9,"Code Enforcement");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (10,"SE High Hzrd Routine Insp");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (11,"SE High Hzrd Routine Reinsp");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (12,"SE Low Hzrd Routine Insp");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (13,"SE Low Hzrd Routine Reinsp");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (14,"PS-Courtesy Visit");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (15,"Food Borne Illness");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (18,"Reinspection - Food Borne Illness");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (20,"PS-Asthma Home Evaluation");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (21,"PS-Baiting");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (22,"PS-Field Consultation Visit");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (23,"PS-Field Survey");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (24,"PS-Location Visit");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (25,"PS-MSR Site Visit");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (26,"PS-Posting");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (27,"Retail Tobacco Routine");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (28,"Retail Tobacco Reinspection - Routine");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (29,"Retail Tobacco Complaint");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (30,"Retail Tobacco Reinspection - Complaint");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (31,"Change of Ownership - Initial");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (32,"Food - Location Visit");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (35,"Massage - Location Visit");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (36,"Housing - Location Visit");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (37,"Green Verification Visit");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (38,"MCD Visit");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (39,"Change of Ownership - Reinspection");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (40,"Routine - New Application");
INSERT INTO tblInspectionTypes_old (InspectionTypeID, InspectionType) VALUES (41,"Reinspection - New Application");
