INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (1,"Food",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (11,"Vegetation/Weeds",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (12,"Pests/Vectors",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (13,"Garbage/Refuse",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (14,"Animals",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (15,"Odors",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (16,"Indoor Air Quality",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (17,"Mold",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (18,"Abandoned Vehicle",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (19,"Hotel Common Areas",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (20,"Hotel Rooms",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (21,"Hotel Outdoor Areas/Lightwells",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (22,"Shelter - Indoor Areas",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (23,"Shelter - Outdoor Areas",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (24,"Drop in Centers - Indoor Areas",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (25,"Drop in Centers - Outdoor Areas",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (27,"Contaminated Equipment",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (28,"Documentation",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (29,"Infectious Waste",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (30,"Miscellaneous",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (31,"Personal Hygiene",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (32,"Practitioner",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (33,"Structural Repairs",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (34,"Vermin",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (35,"Structural Repairs",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (36,"Facility Sanitation",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (37,"Practitioner Hygiene",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (38,"Equipment in Disrepair",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (39,"Vermin",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (40,"Permits and Licenses",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (41,"Smoking",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (42,"Retail Tobacco",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (43,"Massage",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (44,"Laundry",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (45,"A) Smoking",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (46,"B) Noise",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (47,"C) Lead",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (48,"D) Asbestos",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (49,"E) Insanitary",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (50,"F) Housing",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (51,"Cannabis Dispensary",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (52,"Food - Mobile Unit",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (53,"LEA - CIWMB 53",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (54,"LEA - CIWMB 213",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (55,"LEA - CIWMB 93",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (56,"LEA - CIWMB 188",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (57,"LEA - CIWMB 73",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (58,"Solid Waste",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (59,"LEA - CIWMB 52",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (60,"LEA - CIWMB 52A",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (61,"LEA - CIWMB 76",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (62,"LEA - CIWMB 215",NULL);
INSERT INTO tblViolationCategories (ViolationCategoryID, Description, T_Stamp) VALUES (63,"LEA - CIWMB 626",NULL);
